services:
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./BackEnd
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=mongodb://db:27017/
      - MONGO_DB=artisan-marketplace
      - JWT_SECRET=${JWT_SECRET} 
      - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}
      - DEFAULT_USER_PASSWORD=${DEFAULT_USER_PASSWORD}
      - CORS_ORIGINS=${CORS_ORIGINS}
      
    volumes:
      - ./BackEnd/uploads:/app/uploads

  frontend:
    build: ./FrontEnd
    ports:
      - "3000:80" 
    depends_on:
      - backend

  proxy:
    image: nginx:alpine
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./artisan.crt:/etc/nginx/ssl/artisan.crt:ro
      - ./artisan.key:/etc/nginx/ssl/artisan.key:ro
    depends_on:
      - frontend
      - backend

  dbinit:
    image: python:3.11
    container_name: dbinit
    working_dir: /Database/sample_data
    volumes:
      - ./Database:/Database
    depends_on:
      - db
    environment:
      - DATABASE_URL=mongodb://db:27017/
      - MONGO_DB=artisan-marketplace
      - JWT_SECRET=${JWT_SECRET}
      - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}
      - CORS_ORIGINS=${CORS_ORIGINS}
      - DEFAULT_USER_PASSWORD=${DEFAULT_USER_PASSWORD}
    command: >
      sh -c "pip install --default-timeout=100 pymongo passlib 'bcrypt==4.0.1' && python DBinit.py"  

volumes:
  mongo-data: